---
version: "3"

services:
  ingestor:
    container_name: ingestor
    image: node:16.17
    ports:
      - 3000:3000
    # user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
      - ingestor_volume:/home/node/app/node_modules
    command: "npm run dev"

volumes:
  ingestor_volume: