POST http://localhost:3000/ingest
Content-Type: application/json

[{
  "name":"L6-43",
  "q":175.2,
  "dt":"2022-10-02T22:05:00.000Z",
  "quality": "90.54"
},{
  "name":"L5-41",
  "q":179.2,
  "dt":"2022-10-02T22:06:00.000Z",
  "quality": 83.54
}]

###
GET http://localhost:3000/pull
Content-Type: application/json

###
GET http://localhost:3000/pull?dt=2022-10-02T22:10:00.000Z
Content-Type: application/json

###
GET http://localhost:3000/pull-abs?dt=2022-10-02T22:10:00.000Z
Content-Type: application/json


###
POST http://localhost:3000/reset
Content-Type: application/json

###
POST http://localhost:3000/clear-pos?pos=L6-43
Content-Type: application/json



###
GET http://localhost:3000/latest?q=20
Content-Type: application/json

###
GET http://localhost:3000/csv-entries
Content-Type: application/json

###
GET http://localhost:3000/csv-avg
Content-Type: application/json

###
POST http://localhost:3000/ingest
Content-Type: application/json

[{"name":"L5-0035","q":2.0,"dt":"2023-03-09T17:15:00.797","quality":63.0},{"name":"L5-9999","q":1.0,"dt":"2023-03-09T17:15:00.797","quality":96.0},{"name":"L6-0035","q":10.0,"dt":"2023-03-09T17:15:00.797","quality":84.0},{"name":"L6-9999","q":0.0,"dt":"2023-03-09T17:15:00.797","quality":100.0}]